### PR TITLE
Added IncludeErrorDetailt to connection parameters

### PR DESCRIPTION
**Pull request by YohDeadfall**

### CODE REVIEW

**Review by roji — APPROVED** [review]
Thanks!

One suggestion: PostgresException.Detail and PostgresNotice.Detail can be links to the API docs. I think this will need to be done with xref ([see docfx docs](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html)).

**Comment by roji** [comment]
@YohDeadfall here's how to link to the API docs: 9f40e7c48f1f391797b32f31fa2dd2399bd1bccc

**Comment by YohDeadfall** [comment]
Is it enough? I read about some YAML magic also.

**Comment by roji** [comment]
Nope, should be enough.

**Pull request merged**
