### PR TITLE
Add missing namespace for the call to optionsBuilder

### PR DESCRIPTION
**Pull request by SeanKilleen**
Came across this while walking someone else through an example.

### CODE REVIEW

**Comment by roji** [comment]
@SeanKilleen that using shouldn't be needed - what exactly isn't compiling with it?

**Comment by SeanKilleen** [comment]
It's not for code I have in front of me currently, unfortunately, but I'm pretty sure the call to `.UseNpgsql` required it in order to make the extension method available for use.

If you feel strongly that it's correct, I don't have the bandwidth to re-confirm at this time; feel free to close. 👍

**Comment by roji** [comment]
The UseNpgsql extension method is defined on NpgsqlDbContextOptionsExtensions, which is in namespace Microsoft.EntityFrameworkCore - the idea is precisely to have these common extension methods there so that users don't need to include any Npgsql-specific namespaces.

I copy-pasted that code snippet and it seems to compile, can you please re-confirm this?

**Comment by SeanKilleen** [comment]
In that case, I'll assume I must have been off-base here -- sorry about that! Unfortunately, I can't re-confirm as this was a quick troubleshooting session in someone else's codebase with an IDE that wasn't prepared how I'm used to it. Likely a fluke that was resolved through some other means. 

Sorry to take your time!

**Pull request closed without merging**
