### PR TITLE
Add contibutors to the release notes

### PR DESCRIPTION
**Pull request by Brar**
Hey @roji  and @YohDeadfall,
what do you think about this?
If you like it, I can create it for the other releases too.

### CODE REVIEW

**Comment by YohDeadfall** [comment]
Let's replace "Contributors" by "Name" and "Assigned issues" by "Contributions" like [here](https://thanks.rust-lang.org/rust/1.46.0/).

**Comment by Brar** [comment]
> Let's replace "Contributors" by "Name" and "Assigned issues" by "Contributions" like here.

I'm OK with "Name" but I'd rather leave "Assigned issues".
The thinking behind this is that there might be other helpful and valid contributions that we don't highlight there since they don't have assigned issues.

**Comment by Brar** [comment]
Thinking about it, even name isn't quite accurate, since technically it's the GitHub login.

While my name is really Brar yours isn't YohDeadfall 😉

**Comment by YohDeadfall** [comment]
We always can add notes below the list and point non code contributions making an anchor link from the table. This will be also helpful in case of documentation work as an addition to code.

Shhh, don't spoil me (:

**Comment by Brar** [comment]
In case you want to play around with the format:
https://github.com/Brar/RepoExplorer

Help:
```
dotnet run -- -?
```

Example:
```
dotnet run -- -u Npgsql -r Npgsql -o Npgsql-5.0.md -m 5.0
```

Everything but the `-u Npgsql` is optional but might cause a lot of GitHub API queries although it is already pretty optimized not to hit any of the [limits](https://developer.github.com/v4/guides/resource-limitations/).

**Comment by YohDeadfall** [comment]
What I would like see is "thank you" written in the contributors section so it won't be just a static, but a demonstration of our feelings. That's the goal.

**Comment by roji** [comment]
Took me a bit of time to look at this, sorry.

Looks good to me! I'd simplify it though, and do a flat list for all external contributors who contributed to 4.1, rather than breaking it down by patch release.. it would be much terser and I don't think anybody really cares about the different patch releases. I know that you can't filter issues by several milestones with OR (because github sucks), but external contributors have few contributions - we can manually list the issue numbers in parentheses after the contributor name (with links).

For permanent contributors or people with a lot of contributions, we can simply do a different section above or below and not list the contributions, what do you think?

**Comment by YohDeadfall** [comment]
Splitting contributors by member and non-member isn't very inclusive since if thing would go well we should have more external changes, but to do this we also should think about our list of up to grab issues which can be taken.

**Comment by roji** [comment]
> Splitting contributors by member and non-member

Why is that? Some people are permanent and also have write access, and others don't - I don't think there's anything non-inclusive in that ([look at the way EF Core does this](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-ef-core-5-0-preview-8/#thank-you-from-the-team))... We could even put external contributors first, to highlight them, above team members.

But if you feel strongly that we should just put members and non-members together, that's OK too.

**Comment by YohDeadfall** [comment]
I like how the list is organized in EF, we could take that idea, but looking at the Rust example we could see that members could have less points than external contributors. That's the goal for us too (hope it's achievable (: ), so keeping a common list for all contributors is very important.

To optimize the tables made by @Brar we could have multiple columns each per version and one summary because we encourage users to have the latest possible version of the project, and therefore, bug fixes are very important too.

> The following people contributed to 4.1 and made the project better. Thank you very much!

| Name                             | Contributions | 4.1.0 | 4.1.1 | 4.1.2 | 4.1.3 | 4.1.4 | 4.1.5 |
| -------------------------------- | ------------- | ----- | ----- | ----- | ----- | ----- | ----- |
| [@roji](https://github.com/roji) | 45            | 27    | 7     |       | 5     | 6     |       |
| ...                              | ...           | ...   | ...   | ...   | ...   | ...   | ...   |

Individual features which were added should mention their author and not just a link. Maybe even some example and description?

**Comment by YohDeadfall** [comment]
Do you mean just having total?

**Comment by Brar** [comment]
Guys, this is not in the hot path.
It's merely a bike shed next to our great product.

**Review by YohDeadfall — APPROVED** [review]
I'm fine with the current even there is some room for improvements, but we should add "thank you" first before merging this.

**Review by roji — APPROVED** [review]

**Comment by Brar** [comment]
Ok, I gave this another quick look, but I'm really convinced that we shouldn't spend too much time on this.
Apparently we all have the same goals:
1. Give balanced credit to the contributors, where balanced means ongoing contributors should get more visibility than one-off pull requests.
2. Refresh the contributors list with every release, which partly serves 1. by taking the focus away from former contributors while still acknowledging their contributions.
3. Give details about the contributions by putting in links. For now it's links to the assigned GitHub issues but it could be something different.
4. Use as little vertical space as possible to achieve the goals above and not overcomplicate things which would distract users who only glance over the page

I was thinking along the lines of giving a overall list per release where one can see the details for an individual contributor using a [collapsed div](https://getbootstrap.com/docs/4.5/components/collapse/) but then found out that this is supported as of bootstrap 4.0 and we're still tied to the version docfx uses which is 3.7 (see http://www.npgsql.org/styles/docfx.vendor.css).

So for now I'll go ahead and commit this as is (with the "Thank you" amendment as suggested by @YohDeadfall) for our currently available release notes.
After all, the contributors section is in the end of the release notes and you simply don't have to scroll down there, if you aren't interested.

We can and certainly will revisit this at some point.

**Pull request merged**
