### PR TITLE
Update datetime.md

### PR DESCRIPTION
**Pull request by farmergreg**
fix broken links

### CODE REVIEW

**Review by roji — COMMENTED** [review]
I can certainly merge this, but the links aren't broken for me; can you confirm whether they really are broken for you, and how?

Note that there are many other references using html elsewhere in these docs.

**Comment by farmergreg** [comment]
Hi @roji,
I only noticed because my team is trying to figure out how to work with the new way of handling datetimes.

For me, the links do not work at all. They take me to a github 404 page. Changing the suffix to .md fixes the problem for me.

**Comment by farmergreg** [comment]
I think i see what happened: my google search took me to the github repo instead of the main documentation website. So I was trying to use the links from here: 
https://github.com/npgsql/doc/blob/main/conceptual/Npgsql/types/datetime.md

**Comment by roji** [comment]
OK. If we really want to change all the html links to md (no particularly strong reason to do so), I'd rather we did it everywhere in one go...

**Pull request closed without merging**
